#!/usr/bin/env bash
# scripts/generate_report.sh
# Generates a Markdown test report by running all aiview commands
# Output: docs/TEST_REPORT_AUTO.md

set -euo pipefail

# ─── Config ──────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

BINARY="./aiview"
REPORT_FILE="docs/TEST_REPORT_AUTO.md"
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S %Z')

PASS_COUNT=0
FAIL_COUNT=0
SKIP_COUNT=0
REPORT_ROWS=()

# ─── Helpers ─────────────────────────────────────────────────────────────────
run_and_record() {
  local category="$1" name="$2" cmd="$3"
  local output exit_code status

  set +e
  output=$(eval "$cmd" 2>&1)
  exit_code=$?
  set -e

  # Truncate output to first 3 lines for the report
  local short_output
  short_output=$(echo "$output" | head -3 | sed 's/|/\\|/g' | tr '\n' ' ')

  if [[ $exit_code -eq 0 ]]; then
    status="PASS"
    ((PASS_COUNT++))
  else
    status="FAIL"
    ((FAIL_COUNT++))
  fi

  REPORT_ROWS+=("| $category | $name | \`$cmd\` | $status | $exit_code | \`$short_output\` |")
}

# ─── Build ───────────────────────────────────────────────────────────────────
echo "Building aiview..."
if ! go build -o "$BINARY" .; then
  echo "Build failed. Cannot generate report."
  exit 1
fi
echo "Build successful."

# ─── Run tests ───────────────────────────────────────────────────────────────
echo "Running commands..."

# Platform hot commands
run_and_record "Platform" "bilibili hot"          "$BINARY bilibili hot"
run_and_record "Platform" "bilibili hot --json"   "$BINARY bilibili hot --json"
run_and_record "Platform" "douyin hot"            "$BINARY douyin hot"
run_and_record "Platform" "douyin hot --json"     "$BINARY douyin hot --json"
run_and_record "Platform" "xiaohongshu hot"       "$BINARY xiaohongshu hot"
run_and_record "Platform" "xiaohongshu hot --json" "$BINARY xiaohongshu hot --json"

# Global help commands
run_and_record "Global" "analyze trend --help"  "$BINARY analyze trend --help"
run_and_record "Global" "compare --help"        "$BINARY compare --help"
run_and_record "Global" "schedule --help"       "$BINARY schedule --help"
run_and_record "Global" "dashboard --help"      "$BINARY dashboard --help"
run_and_record "Global" "tui --help"            "$BINARY tui --help"
run_and_record "Global" "export --help"         "$BINARY export --help"
run_and_record "Global" "root --help"           "$BINARY --help"

# Subcommand help
run_and_record "Subcommand" "schedule add --help"    "$BINARY schedule add --help"
run_and_record "Subcommand" "schedule list --help"   "$BINARY schedule list --help"
run_and_record "Subcommand" "schedule remove --help" "$BINARY schedule remove --help"

# ─── Generate report ────────────────────────────────────────────────────────
TOTAL=$((PASS_COUNT + FAIL_COUNT + SKIP_COUNT))

mkdir -p docs

cat > "$REPORT_FILE" <<HEADER
# Automated Test Report

- **Generated**: $TIMESTAMP
- **Binary**: \`$BINARY\`
- **Total tests**: $TOTAL | **Passed**: $PASS_COUNT | **Failed**: $FAIL_COUNT | **Skipped**: $SKIP_COUNT

## Results

| Category | Test Name | Command | Status | Exit Code | Output (truncated) |
|----------|-----------|---------|--------|-----------|--------------------|
HEADER

for row in "${REPORT_ROWS[@]}"; do
  echo "$row" >> "$REPORT_FILE"
done

cat >> "$REPORT_FILE" <<FOOTER

## Summary

- Pass rate: $(( PASS_COUNT * 100 / (TOTAL > 0 ? TOTAL : 1) ))%
- Total commands tested: $TOTAL

---
*This report was auto-generated by \`scripts/generate_report.sh\`.*
FOOTER

echo ""
echo "Report written to: $REPORT_FILE"
echo "  Passed: $PASS_COUNT / $TOTAL"
echo "  Failed: $FAIL_COUNT / $TOTAL"
